// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyDiemSV.Data;

#nullable disable

namespace QuanLyDiemSV.Migrations
{
    [DbContext(typeof(QLDSVDbContext))]
    [Migration("20260122145228_KhoiTaoCSDL_Final")]
    partial class KhoiTaoCSDL_Final
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyDiemSV.Data.DieuKienMonHoc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("MaMon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaMonTienQuyet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ID");

                    b.HasIndex("MaMon");

                    b.HasIndex("MaMonTienQuyet");

                    b.ToTable("DieuKienMonHoc");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.GiangVien", b =>
                {
                    b.Property<string>("MaGV")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HocVi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SDT")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("MaGV");

                    b.HasIndex("MaKhoa");

                    b.HasIndex("UserID");

                    b.HasIndex(new[] { "Email" }, "UQ__GiangVie__A9D105342D7F3DF8")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("GiangVien");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.HocKy", b =>
                {
                    b.Property<string>("MaHK")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("NamHocBatDau")
                        .HasColumnType("int");

                    b.Property<int?>("NamHocKetThuc")
                        .HasColumnType("int");

                    b.Property<string>("TenHK")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHK");

                    b.ToTable("HocKy");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.KetQuaHocTap", b =>
                {
                    b.Property<int>("MaKQ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKQ"));

                    b.Property<decimal?>("DiemCC")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal?>("DiemCK")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<string>("DiemChu")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasComputedColumnSql("(case when ((isnull([DiemCC],(0))*(0.1)+isnull([DiemGK],(0))*(0.3))+isnull([DiemCK],(0))*(0.6))>=(8.5) then 'A' when ((isnull([DiemCC],(0))*(0.1)+isnull([DiemGK],(0))*(0.3))+isnull([DiemCK],(0))*(0.6))>=(7.0) then 'B' when ((isnull([DiemCC],(0))*(0.1)+isnull([DiemGK],(0))*(0.3))+isnull([DiemCK],(0))*(0.6))>=(5.5) then 'C' when ((isnull([DiemCC],(0))*(0.1)+isnull([DiemGK],(0))*(0.3))+isnull([DiemCK],(0))*(0.6))>=(4.0) then 'D' else 'F' end)", false);

                    b.Property<decimal?>("DiemGK")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal?>("DiemTongKet")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(4, 2)")
                        .HasComputedColumnSql("(CONVERT([decimal](4,2),(isnull([DiemCC],(0))*(0.1)+isnull([DiemGK],(0))*(0.3))+isnull([DiemCK],(0))*(0.6)))", true);

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaLHP")
                        .HasColumnType("int");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaKQ");

                    b.HasIndex("MaLHP");

                    b.HasIndex(new[] { "MaSV", "MaLHP" }, "UQ_SinhVien_LopHP")
                        .IsUnique();

                    b.ToTable("KetQuaHocTap");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly?>("NgayThanhLap")
                        .HasColumnType("date");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TruongKhoa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.LopHanhChinh", b =>
                {
                    b.Property<string>("MaLop")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaGVCN")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaNganh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NienKhoa")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaGVCN");

                    b.HasIndex("MaNganh");

                    b.ToTable("LopHanhChinh");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.LopHocPhan", b =>
                {
                    b.Property<int>("MaLHP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLHP"));

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaHK")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MaMon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PhongHoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SiSoToiDa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(60);

                    b.Property<string>("TenLopHP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("MaLHP");

                    b.HasIndex("MaGV");

                    b.HasIndex("MaHK");

                    b.HasIndex("MaMon");

                    b.ToTable("LopHocPhan");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.MonHoc", b =>
                {
                    b.Property<string>("MaMon")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("SoTietLyThuyet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("SoTietThucHanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaMon");

                    b.HasIndex("MaKhoa");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.Nganh", b =>
                {
                    b.Property<string>("MaNganh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenNganh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNganh");

                    b.HasIndex("MaKhoa");

                    b.ToTable("Nganh");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Role__8A2B61608B19F6E4")
                        .IsUnique();

                    b.ToTable("Role");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CCCD")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("MaSV");

                    b.HasIndex("MaLop");

                    b.HasIndex("UserID");

                    b.HasIndex(new[] { "CCCD" }, "UQ__SinhVien__A955A0AA5F826F6E")
                        .IsUnique()
                        .HasFilter("[CCCD] IS NOT NULL");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.UserAccount", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.HasIndex(new[] { "Username" }, "UQ__UserAcco__536C85E4511305A8")
                        .IsUnique();

                    b.ToTable("UserAccount");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.DieuKienMonHoc", b =>
                {
                    b.HasOne("QuanLyDiemSV.Data.MonHoc", "MaMonNavigation")
                        .WithMany("DieuKienMonHocMaMonNavigation")
                        .HasForeignKey("MaMon")
                        .IsRequired();

                    b.HasOne("QuanLyDiemSV.Data.MonHoc", "MaMonTienQuyetNavigation")
                        .WithMany("DieuKienMonHocMaMonTienQuyetNavigation")
                        .HasForeignKey("MaMonTienQuyet")
                        .IsRequired();

                    b.Navigation("MaMonNavigation");

                    b.Navigation("MaMonTienQuyetNavigation");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.GiangVien", b =>
                {
                    b.HasOne("QuanLyDiemSV.Data.Khoa", "MaKhoaNavigation")
                        .WithMany("GiangVien")
                        .HasForeignKey("MaKhoa")
                        .IsRequired();

                    b.HasOne("QuanLyDiemSV.Data.UserAccount", "User")
                        .WithMany("GiangVien")
                        .HasForeignKey("UserID");

                    b.Navigation("MaKhoaNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.KetQuaHocTap", b =>
                {
                    b.HasOne("QuanLyDiemSV.Data.LopHocPhan", "MaLHPNavigation")
                        .WithMany("KetQuaHocTap")
                        .HasForeignKey("MaLHP")
                        .IsRequired();

                    b.HasOne("QuanLyDiemSV.Data.SinhVien", "MaSVNavigation")
                        .WithMany("KetQuaHocTap")
                        .HasForeignKey("MaSV")
                        .IsRequired();

                    b.Navigation("MaLHPNavigation");

                    b.Navigation("MaSVNavigation");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.LopHanhChinh", b =>
                {
                    b.HasOne("QuanLyDiemSV.Data.GiangVien", "MaGVCNNavigation")
                        .WithMany("LopHanhChinh")
                        .HasForeignKey("MaGVCN");

                    b.HasOne("QuanLyDiemSV.Data.Nganh", "MaNganhNavigation")
                        .WithMany("LopHanhChinh")
                        .HasForeignKey("MaNganh")
                        .IsRequired();

                    b.Navigation("MaGVCNNavigation");

                    b.Navigation("MaNganhNavigation");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.LopHocPhan", b =>
                {
                    b.HasOne("QuanLyDiemSV.Data.GiangVien", "MaGVNavigation")
                        .WithMany("LopHocPhan")
                        .HasForeignKey("MaGV")
                        .IsRequired();

                    b.HasOne("QuanLyDiemSV.Data.HocKy", "MaHKNavigation")
                        .WithMany("LopHocPhan")
                        .HasForeignKey("MaHK")
                        .IsRequired();

                    b.HasOne("QuanLyDiemSV.Data.MonHoc", "MaMonNavigation")
                        .WithMany("LopHocPhan")
                        .HasForeignKey("MaMon")
                        .IsRequired();

                    b.Navigation("MaGVNavigation");

                    b.Navigation("MaHKNavigation");

                    b.Navigation("MaMonNavigation");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.MonHoc", b =>
                {
                    b.HasOne("QuanLyDiemSV.Data.Khoa", "MaKhoaNavigation")
                        .WithMany("MonHoc")
                        .HasForeignKey("MaKhoa");

                    b.Navigation("MaKhoaNavigation");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.Nganh", b =>
                {
                    b.HasOne("QuanLyDiemSV.Data.Khoa", "MaKhoaNavigation")
                        .WithMany("Nganh")
                        .HasForeignKey("MaKhoa")
                        .IsRequired();

                    b.Navigation("MaKhoaNavigation");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.SinhVien", b =>
                {
                    b.HasOne("QuanLyDiemSV.Data.LopHanhChinh", "MaLopNavigation")
                        .WithMany("SinhVien")
                        .HasForeignKey("MaLop")
                        .IsRequired();

                    b.HasOne("QuanLyDiemSV.Data.UserAccount", "User")
                        .WithMany("SinhVien")
                        .HasForeignKey("UserID");

                    b.Navigation("MaLopNavigation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.UserAccount", b =>
                {
                    b.HasOne("QuanLyDiemSV.Data.Role", "Role")
                        .WithMany("UserAccount")
                        .HasForeignKey("RoleID")
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.GiangVien", b =>
                {
                    b.Navigation("LopHanhChinh");

                    b.Navigation("LopHocPhan");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.HocKy", b =>
                {
                    b.Navigation("LopHocPhan");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.Khoa", b =>
                {
                    b.Navigation("GiangVien");

                    b.Navigation("MonHoc");

                    b.Navigation("Nganh");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.LopHanhChinh", b =>
                {
                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.LopHocPhan", b =>
                {
                    b.Navigation("KetQuaHocTap");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.MonHoc", b =>
                {
                    b.Navigation("DieuKienMonHocMaMonNavigation");

                    b.Navigation("DieuKienMonHocMaMonTienQuyetNavigation");

                    b.Navigation("LopHocPhan");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.Nganh", b =>
                {
                    b.Navigation("LopHanhChinh");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.Role", b =>
                {
                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.SinhVien", b =>
                {
                    b.Navigation("KetQuaHocTap");
                });

            modelBuilder.Entity("QuanLyDiemSV.Data.UserAccount", b =>
                {
                    b.Navigation("GiangVien");

                    b.Navigation("SinhVien");
                });
#pragma warning restore 612, 618
        }
    }
}
